os:
    - linux
sudo: false
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++6
            - fonts-droid
before_script:
    - git clone https://github.com/flutter/flutter.git --depth 1
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - flutter doctor
cache:
    directories:
        - $HOME/.pub-cache
script:
    - tools/travis.sh
